default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: cafeautomatico_development

test:
  <<: *default
  database: cafeautomatico_test

staging:
  <<: *default
  database: cafeautomatico_staging

production:
  <<: *default
  database: cafeautomatico_production
